
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Aerospace Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 4227 Sheaf Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Aerospace Engineering tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Aerospace Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Animation course talk','Media Arts & Comms','Subject Talk','11:00','11:30','Room 2502 Harmer Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Animation facilities tour','Media Arts & Comms','Tour','12:00','12:30','Room 2502 Harmer Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Animation session','Media Arts & Comms','Network/Refreshments','12:30','13:30','STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Animation taster session','Media Arts & Comms','Taster Session','11:30','12:00','Room 2502 Harmer Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Automotive Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3107 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Automotive Engineering  tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Automotive Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Business and Information Technology talk','Computing','Subject Talk','11:00','12:00','Room 9135 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Business and Information Technology tour','Computing','Tour','12:00','13:00','Room 9135 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Business and Information Technology session','Computing','Network/Refreshments','13:00','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Chemical Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3113 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Chemical Engineering tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Chemical Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Forensics, Security and Networks talk','Computing','Subject Talk','11:00','12:00','Room 9006 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Forensics, Security and Networks tour','Computing','Tour','12:00','13:00','Start in 9307 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Forensics, Security and Networks session','Computing','Network/Refreshments','13:00','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Science for Games  talk','Computing','Subject Talk','11:00','12:00','Room 9005 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Science for Games tour','Computing','Tour','12:00','13:00','Start in 9336 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Science for Games session','Computing','Network/Refreshments','13:00','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Systems Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3119 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Systems Engineering tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computer Systems Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computing  talk','Computing','Subject Talk','11:00','12:00','Room 9003 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computing tour','Computing','Tour','12:00','13:00','Start in 9341 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Computing session','Computing','Network/Refreshments','13:00','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Digital Media Production  talk','Media Arts & Comms','Subject Talk','11:00','11:30','Room 5520 Surrey Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Digital Media Production  tour','Media Arts & Comms','Tour','12:00','12:30','Start from Room 5520 Surrey Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Digital Media Production session','Media Arts & Comms','Network/Refreshments','12:30','13:30','STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Digital Media Production taster session','Media Arts & Comms','Taster Session','11:30','12:00','Start from Room 5520 Surrey Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Electrical and Electronic Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3108 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Electrical and Electronic Engineering tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Electrical and Electronic Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Computing  session','Computing','Network/Refreshments','13:00','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Computing talk','Computing','Subject Talk','11:00','12:00','Room 9315 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Computing tour','Computing','Tour','12:00','13:00','Start in Room 9315 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Engineering and Maths talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3115 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Engineering and Maths tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Engineering and Maths session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Media Arts and Communication talk','Media Arts & Comms','Subject Talk','11:00','11:30','Room 9132 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Media Arts and Communication tour','Media Arts & Comms','Tour','12:15','12:30','Room 9132 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Media Arts and Communication taster session','Media Arts & Comms','Taster Session','11:30','12:00','Room 9132 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Extended Degree in Media Arts session','Media Arts & Comms','Network/Refreshments','12:30','13:30','STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Film and Media Production talk','Media Arts & Comms','Subject Talk','11:00','11:45','Room 1025 Owen Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Film and Media Production tour','Media Arts & Comms','Tour','12:15','12:45','Room 2301 Harmer Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Film and Media Production session','Media Arts & Comms','Network/Refreshments','12:30','13:30','STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Film and Media Production taster session','Media Arts & Comms','Taster Session','11:45','12:15','Room 2301 Harmer Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Food Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3105 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Food Engineering tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Food Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Games Design talk','Media Arts & Comms','Subject Talk','11:00','11:30','Room 9231 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Games Design tour','Media Arts & Comms','Tour','12:00','12:30','Start in Room 9231 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Games Design session','Media Arts & Comms','Network/Refreshments','12:30','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Games Design taster session','Media Arts & Comms','Taster Session','11:30','12:00','Room 9231 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Information Technology top ups talk','Computing','Subject Talk','11:00','12:00','Room 9315 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Information Technology top ups tour','Computing','Tour','12:00','13:00','Room 9315 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Information Technology top ups session','Computing','Network/Refreshments','13:00','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Journalism talk','Media Arts & Comms','Subject Talk','11:00','11:30','Room 9130 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Journalism tour','Media Arts & Comms','Tour','12:15','12:30','Start in Room 9205 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Journalism session','Media Arts & Comms','Network/Refreshments','12:30','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Journalism taster session','Media Arts & Comms','Taster Session','11:30','12:15','Room 9205 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Materials Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3104 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Materials Engineering tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Materials Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Mathematics talk and tour','Engineering/Maths/Physics','Subject Talk','11:00','12:30','Room 609 Norfolk Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Mathematics session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Mechanical Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3021 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Mechanical Engineering tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Mechanical Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Media talk','Media Arts & Comms','Subject Talk','12:15','13:00','Room 9235 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Media tour','Media Arts & Comms','Tour','12:00','12:15','Room 9235 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Media session','Media Arts & Comms','Network/Refreshments','12:15','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Media taster session','Media Arts & Comms','Taster Session','11:00','12:00','Room 9235 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Physics talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3114 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Physics tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Physics session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Public Relations talk','Media Arts & Comms','Subject Talk','11:00','11:30','Room 9228 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Public Relations tour','Media Arts & Comms','Tour','12:15','12:30','Room 9228 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Public Relations session','Media Arts & Comms','Network/Refreshments','12:30','13:30','Cantor Cafe and Cantor Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Public Relations taster session','Media Arts & Comms','Taster Session','11:30','12:15','Room 9228 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Railway Engineering talk','Engineering/Maths/Physics','Subject Talk','11:00','11:45','Room 3106 Eric Mensforth Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Railway Engineering tour','Engineering/Maths/Physics','Tour','11:45','12:30','Meet in Hertha Ayrton STEM Centre');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Railway Engineering session','Engineering/Maths/Physics','Network/Refreshments','12:30','13:30','Faculty Space STEM Atrium');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Software Engineering and Computer Science talk','Computing','Subject Talk','11:00','12:00','Room 9002 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Software Engineering and Computer Science tour','Computing','Tour','12:00','13:00','Start in Room 9310 Cantor Building');
INSERT INTO Courses(Subject,Department,Session,Start,Finish,Venue) VALUES ('Software Engineering and Computer Science session','Computing','Network/Refreshments','13:00','13:30','Cantor Cafe and Cantor Atrium');
